using Banking.CQRS.Core.Messages;

namespace Banking.CQRS.Core.Events
{
    /// <summary>
    /// Represents the base class for all the events generated by the system.
    /// </summary>
    public class EventBase : Message
    {

        public int Version { get; set; }

        public EventBase(string id) : base(id)
        {


        }
    }
}
