namespace Banking.CQRS.Core.Messages
{
    /// <summary>
    /// Base class for all the messages generated by the system.
    /// </summary>
    public abstract class Message
    {
        public string Id { get; set; }

        public Message(string id)
        {
            Id = id;
        }

    }
}
